Homework 1
OlenaArshan/Homework2_Calculator pull request #1
Opened 2022-06-03 07:10 UTC by OlenaArshan

Current value and profit/loss calculator. Please review tasks from homework 2.

2022-06-03 09:43 UTC, alberttashu requested changes

2022-06-03 09:43 UTC, alberttashu commented on Program.cs
> +            double tradePrice = double.Parse(userInput ?? "0");
you can remove this condition - `userInput ?? "0"`; 
If user won't input anything in the console, Console.ReadLine would return `string.Empty`;
So a better way to do such condition would be 
`tradePrice = string.IsNullOrEmpty(userInput) ? 0 : double.Parse(userInput)`

2022-06-03 09:43 UTC, alberttashu commented on Program.cs
> +            TransactionType trcType = (TransactionType)Enum.Parse(typeof(TransactionType), userInput ?? "0", true);
this condition doesn't make sense here - `userInput ?? "0"`
default value "0" won't be parsed to TransactionType anyway

2022-06-03 09:43 UTC, alberttashu commented on Program.cs
> +            double tradePrice = double.Parse(userInput ?? "0");
and please consider changing all occurences of `userInput ?? "0"`

2022-06-06 10:41 UTC, OlenaArshan commented
Thank you for comments, I made changes.

2022-06-06 10:42 UTC, merged